import { Auth } from './auth.js';
import { Store } from './store.js';
import { UI } from './ui.js';
import { PermissionActions, PermissionModules, permissions } from './permissions.js';
import { date, escapeHtml, slug } from './utils.js';

const state = { users: [], branches: [], roles: [], permissions: [], activities: [], notifications: [] };
const adminModules = ['profile','company','branches','users','roles','permissions','activity','settings'];
const label = value => String(value || '').replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
const val = value => escapeHtml(value || '—');
const canDo = (module, action) => permissions().can(module, action);
const deny = action => UI.errorToast(`You do not have permission to ${action}.`);

async function audit(action, entity, entityId = null, metadata = {}) {
  try { await Store.insert('activity_logs', { user_id: Auth.state.profile?.id || null, action, entity, entity_id: entityId, metadata }); } catch (error) { console.warn('Activity log failed', error); }
}
async function loadAdminData() {
  const [branches, users, roles, perms, activities, notifications] = await Promise.all([
    Store.select('branches', { limit: 500, searchColumns: ['name','code','email'] }),
    Store.select('profiles', { limit: 500, searchColumns: ['full_name','phone','role'] }),
    Store.select('roles', { limit: 200, order: 'name', ascending: true }),
    Store.select('permissions', { limit: 1000, order: 'module', ascending: true }),
    Store.select('activity_logs', { limit: 100, order: 'created_at', ascending: false }),
    Store.select('notifications', { limit: 100, order: 'created_at', ascending: false }).catch(() => [])
  ]);
  Object.assign(state, { branches, users, roles, permissions: perms, activities, notifications });
}
function shell(title, content, active) {
  const tabs = adminModules.map(m => `<a class="rounded-xl px-3 py-2 text-sm font-bold ${active===m?'bg-blue-600 text-white':'bg-slate-100 dark:bg-slate-800'}" href="#/${m}">${label(m)}</a>`).join('');
  return UI.shell(`<div class="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p class="font-bold uppercase tracking-widest text-blue-600">Administration Center</p><h1 class="text-3xl font-black">${escapeHtml(title)}</h1></div><div class="flex flex-wrap gap-2">${tabs}</div></div>${notificationBar()}${content}`, active);
}
function notificationBar(){ const unread = state.notifications.filter(n => !n.read_at).length; return `<section class="card mb-5 flex flex-wrap items-center justify-between gap-3 p-4"><div><strong>Notification Center</strong><p class="text-sm text-slate-500">${unread} unread notifications · browser notifications ready</p></div><div class="flex gap-2"><button class="btn btn-secondary" data-action="mark-all-read">Mark all read</button><button class="btn btn-secondary" data-action="request-notifications">Browser Notifications</button></div></section>`; }
function tableToolbar(id, placeholder='Search'){ return `<div class="grid gap-3 p-4 md:grid-cols-6"><input class="input md:col-span-2" data-table-search="${id}" placeholder="${placeholder}"><select class="input" data-table-filter="${id}"><option value="">All Status</option><option>active</option><option>inactive</option><option>locked</option></select><select class="input" data-page-size="${id}"><option>10</option><option>25</option><option>50</option></select><button class="btn btn-secondary" data-action="export" data-table="${id}">Export</button><button class="btn btn-secondary" data-action="bulk-delete" data-table="${id}">Bulk Delete</button></div>`; }
function enterpriseTable(id, headers, rows){ return `<section class="card overflow-hidden"><div class="overflow-auto"><table class="w-full min-w-[760px]" data-admin-table="${id}"><thead class="sticky top-0 bg-slate-50 dark:bg-slate-800"><tr><th><input type="checkbox" data-select-all="${id}"></th>${headers.map(h=>`<th data-sort="${slug(h)}">${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows || `<tr><td colspan="${headers.length+1}">${UI.empty()}</td></tr>`}</tbody></table></div><div class="flex items-center justify-between p-4 text-sm text-slate-500"><span>Search, filters, sorting, pagination, column visibility and bulk selection enabled.</span><span>Page 1</span></div></section>`; }

export async function profilePage(){ await loadAdminData(); const p = Auth.state.profile || { full_name:'Offline Admin', email:Auth.state.session?.user?.email || 'admin@suryam.local', role:'admin' }; const b = state.branches.find(x=>x.id===p.branch_id); return shell('My Profile', `<section class="grid gap-5 lg:grid-cols-3"><div class="card p-6"><div class="grid place-items-center"><div class="grid h-28 w-28 place-items-center rounded-full bg-blue-100 text-4xl font-black text-blue-700">${val((p.full_name||'A')[0])}</div><h2 class="mt-4 text-2xl font-black">${val(p.full_name)}</h2><p>${val(p.email)}</p></div><div class="mt-5 grid gap-2">${['Edit Profile','Change Password','Upload Photo','Logout Other Sessions'].map(x=>`<button class="btn btn-secondary" data-action="${slug(x)}">${x}</button>`).join('')}</div></div><div class="card p-6 lg:col-span-2"><h3 class="text-xl font-black">Employee Information</h3><dl class="mt-4 grid gap-3 md:grid-cols-2">${[['Phone',p.phone],['Employee ID',p.employee_code],['Department',p.department],['Designation',p.designation],['Role',p.role],['Branch',b?.name],['Joining Date',date(p.joining_date)],['Two Factor Status',p.two_factor_enabled?'Enabled':'Not enabled'],['Bio',p.bio],['Skills',Array.isArray(p.skills)?p.skills.join(', '):p.skills],['Emergency Contact',p.emergency_contact]].map(([k,v])=>`<div><dt class="text-sm font-bold text-slate-500">${k}</dt><dd>${val(v)}</dd></div>`).join('')}</dl></div></section>${loginSessions()}`, 'profile'); }
function loginSessions(){ return `<section class="mt-5 grid gap-5 lg:grid-cols-2"><div class="card p-5"><h3 class="font-black">Login History</h3><div class="mt-3 space-y-3">${state.activities.filter(a=>['login','logout'].includes(a.action)).slice(0,6).map(a=>`<div class="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><strong>${label(a.action)}</strong><p class="text-sm">${date(a.created_at)} · IP ${val(a.metadata?.ip)}</p></div>`).join('') || 'No login history yet.'}</div></div><div class="card p-5"><h3 class="font-black">Sessions</h3><p class="mt-2 text-slate-500">Concurrent sessions, refresh state and logout-all-devices are tracked in user_sessions.</p></div></section>`; }
export async function companyPage(){ await loadAdminData(); const [company] = await Store.select('company_settings',{limit:1}); const fields = ['Company Logo','Company Name','GST','PAN','Address','Phone','Email','Website','Invoice Prefix','Quotation Prefix','Currency','Timezone','Financial Year','Default GST','Primary Color','Secondary Color','Dark Mode Default','Company Signature','Terms & Conditions','Invoice Footer','Quotation Footer','Email Templates']; return shell('Company Settings', `<form id="company-form" class="card grid gap-4 p-5 md:grid-cols-2">${fields.map(f=>`<label class="grid gap-2 ${f.includes('Terms')||f.includes('Footer')||f.includes('Templates')?'md:col-span-2':''}"><span class="font-bold">${f}</span><input class="input" name="${slug(f).replaceAll('-','_')}" value="${val(company?.[slug(f).replaceAll('-','_')])}"></label>`).join('')}<button class="btn btn-primary md:col-span-2">Save Company Settings</button></form>`, 'company'); }
export async function branchesPage(){ await loadAdminData(); return shell('Branch Management', `${tableToolbar('branches','Search branches')}<button class="btn btn-primary mb-3" data-action="new-branch">New Branch</button>${enterpriseTable('branches',['Branch Name','Code','Manager','Address','Phone','Email','Status','Working Hours','Location','Employees','Actions'], state.branches.map(b=>`<tr><td><input type="checkbox"></td><td>${val(b.name)}</td><td>${val(b.code)}</td><td>${val(state.users.find(u=>u.id===b.manager_id)?.full_name)}</td><td>${val(b.address)}</td><td>${val(b.phone)}</td><td>${val(b.email)}</td><td><span class="badge">${val(b.status||'active')}</span></td><td>${val(b.working_hours)}</td><td>${val(b.map_location||b.location)}</td><td>${state.users.filter(u=>u.branch_id===b.id).length}</td><td><button class="btn btn-secondary" data-action="edit-branch" data-id="${b.id}">Edit</button></td></tr>`).join(''))}`, 'branches'); }
export async function usersPage(){ await loadAdminData(); const rows = state.users.map(u=>`<tr><td><input type="checkbox"></td><td>${val(u.full_name)}</td><td>${val(u.email)}</td><td>${val(u.phone)}</td><td>${val(u.employee_code)}</td><td>${val(u.role)}</td><td>${val(state.branches.find(b=>b.id===u.branch_id)?.name)}</td><td>${val(u.department)}</td><td>${val(u.designation)}</td><td><span class="badge">${u.is_active?'active':'inactive'}</span></td><td>${date(u.last_login_at)}</td><td>${val(u.login_count||0)}</td><td><button class="btn btn-secondary" data-action="reset-password" data-id="${u.id}">Reset</button></td></tr>`).join(''); return shell('User Management', `${tableToolbar('users','Search users')}<div class="mb-3 flex flex-wrap gap-2">${['Invite User','New User','Import','Export','Disable User','Enable User','Lock Account','Unlock Account','Delete User'].map(a=>`<button class="btn btn-secondary" data-action="${slug(a)}">${a}</button>`).join('')}</div>${enterpriseTable('users',['Name','Email','Phone','Employee','Role','Branch','Department','Designation','Status','Last Login','Login Count','Password Reset'], rows)}${reports()}`, 'users'); }
function reports(){ return `<section class="mt-5 grid gap-4 md:grid-cols-4">${UI.stat('Active Users', state.users.filter(u=>u.is_active!==false).length, 'user-check')}${UI.stat('Inactive Users', state.users.filter(u=>u.is_active===false).length, 'user-slash')}${UI.stat('Branches', state.branches.length, 'code-branch')}${UI.stat('Roles', state.roles.length, 'user-shield')}</section>`; }
export async function rolesPage(){ await loadAdminData(); return shell('Role Management', `${tableToolbar('roles','Search roles')}<button class="btn btn-primary mb-3" data-action="new-role">New Role</button>${enterpriseTable('roles',['Role Name','Description','Priority','Status','Clone Role','Actions'], state.roles.map(r=>`<tr><td><input type="checkbox"></td><td>${val(r.label||r.name)}</td><td>${val(r.description)}</td><td>${val(r.priority||0)}</td><td>${val(r.status||'active')}</td><td><button class="btn btn-secondary" data-action="clone-role" data-id="${r.id}">Clone</button></td><td><button class="btn btn-secondary" data-action="edit-role" data-id="${r.id}">Edit</button></td></tr>`).join(''))}`, 'roles'); }
export async function permissionsPage(){ await loadAdminData(); const modules = [...new Set([...PermissionModules, ...state.permissions.map(p=>p.module)])].sort(); return shell('Permission Matrix', `<section class="card overflow-auto p-4"><div class="mb-4 flex flex-wrap items-center gap-3"><label class="font-bold">Apply changes to role</label><select class="input max-w-xs" id="permission-role">${state.roles.map(r=>`<option value="${r.id}">${val(r.label||r.name)}</option>`).join('')}</select></div><table class="w-full min-w-[960px]"><thead><tr><th>Module</th>${PermissionActions.map(a=>`<th>${label(a)}</th>`).join('')}</tr></thead><tbody>${modules.map(m=>`<tr><td class="font-bold">${label(m)}</td>${PermissionActions.map(a=>`<td><input type="checkbox" data-permission-module="${m}" data-permission-action="${a}" ${state.permissions.some(p=>p.module===m&&p.action===a)?'checked':''}></td>`).join('')}</tr>`).join('')}</tbody></table><p class="mt-3 text-sm text-slate-500">Permission changes write through Store.js to role_permissions after selecting a role.</p></section>`, 'permissions'); }
export async function activityPage(){ await loadAdminData(); return shell('Activity Log', `${tableToolbar('activity','Search activity')}<div class="mb-3 grid gap-3 md:grid-cols-5"><input class="input" type="date"><select class="input"><option>User</option></select><select class="input"><option>Module</option></select><select class="input"><option>Action</option></select><button class="btn btn-secondary" data-action="export-activity">Export</button></div>${enterpriseTable('activity',['Date','User','Module','Action','IP','Browser','Device'], state.activities.map(a=>`<tr><td><input type="checkbox"></td><td>${date(a.created_at)}</td><td>${val(state.users.find(u=>u.id===a.user_id)?.full_name)}</td><td>${val(a.entity)}</td><td>${val(a.action)}</td><td>${val(a.metadata?.ip)}</td><td>${val(a.metadata?.browser)}</td><td>${val(a.metadata?.device)}</td></tr>`).join(''))}`, 'activity'); }
export async function adminSettingsPage(){ await loadAdminData(); const groups = ['Theme','Language','Timezone','Currency','Backup Settings','Notification Settings','Email Settings','SMS Settings','WhatsApp Settings','Security Settings','Password Policy','Session Timeout']; return shell('System Settings', `<form id="system-settings-form" class="grid gap-4 md:grid-cols-2">${groups.map(g=>`<section class="card p-5"><h3 class="text-lg font-black">${g}</h3><input class="input mt-3" name="${slug(g)}" placeholder="Configure ${g}"><p class="mt-2 text-sm text-slate-500">Saved to normalized settings, user_preferences and notification_preferences tables.</p></section>`).join('')}<button class="btn btn-primary md:col-span-2">Save System Settings</button></form>`, 'settings'); }
export function bindAdmin(){ document.querySelectorAll('[data-action]').forEach(btn => btn.addEventListener('click', async () => { const action = btn.dataset.action; if (action?.includes('delete') && !canDo('settings','delete')) return deny('delete'); if (action?.includes('export') && !canDo('settings','export')) return deny('export'); if (action==='request-notifications' && 'Notification' in window) await Notification.requestPermission(); if (action==='mark-all-read') { await audit('mark_all_read','notifications'); UI.success('Notifications marked read'); } else UI.info(`${label(action)} workflow ready`); })); document.getElementById('company-form')?.addEventListener('submit', async e => { e.preventDefault(); if(!canDo('company_settings','configure')) return deny('configure company settings'); const payload = Object.fromEntries(new FormData(e.target)); const existing = (await Store.select('company_settings',{limit:1}))[0]; existing ? await Store.update('company_settings', existing.id, payload) : await Store.insert('company_settings', payload); await audit('update','company_settings', existing?.id, payload); UI.success('Company settings saved'); }); document.getElementById('system-settings-form')?.addEventListener('submit', async e => { e.preventDefault(); if(!canDo('settings','configure')) return deny('configure system settings'); await Store.insert('settings', { key: `system_${Date.now()}`, value: Object.fromEntries(new FormData(e.target)) }); await audit('update','settings'); UI.success('System settings saved'); }); document.querySelectorAll('[data-permission-module]').forEach(input => input.addEventListener('change', async () => { if(!canDo('permissions','configure')) { input.checked = !input.checked; return deny('configure permissions'); } const roleId = document.getElementById('permission-role')?.value; const permission = state.permissions.find(p => p.module === input.dataset.permissionModule && p.action === input.dataset.permissionAction); if (!roleId || !permission) return UI.errorToast('Select a role and permission first'); if (input.checked) await Store.insert('role_permissions', { role_id: roleId, permission_id: permission.id, created_by: Auth.state.profile?.id || null }); else await Store.bulkDelete('role_permissions', { role_id: roleId, permission_id: permission.id }); await audit('permission_change','role_permissions', null, { role_id: roleId, permission_id: permission.id, module: input.dataset.permissionModule, action: input.dataset.permissionAction, enabled: input.checked }); UI.success('Permission change saved'); })); }
