import { AppConfig } from './config.js';
import { Router } from './router.js';
import { UI } from './ui.js';
import { dashboardPage } from './dashboard.js';
import { crmPage, bindCrm } from './crm.js';
import { customersPage } from './customers.js'; import { inventoryPage } from './inventory.js'; import { installationPage } from './installation.js'; import { servicePage } from './service.js'; import { amcPage } from './amc.js'; import { employeesPage } from './employees.js'; import { accountsPage } from './accounts.js'; import { reportsPage } from './reports.js'; import { settingsPage } from './settings.js';
import { loginPage, bindLogin } from './auth.js';

const app = document.getElementById('app');
document.documentElement.classList.toggle('dark', localStorage.theme === 'dark');
function mount(html, { publicLayout = false, after = () => {} } = {}) { document.getElementById('public-header').innerHTML = publicLayout ? UI.publicHeader() : ''; document.getElementById('public-footer').innerHTML = publicLayout ? UI.publicFooter() : ''; app.innerHTML = html; document.getElementById('theme-toggle')?.addEventListener('click', toggleTheme); after(); }
function toggleTheme(){ document.documentElement.classList.toggle('dark'); localStorage.theme = document.documentElement.classList.contains('dark') ? 'dark' : 'light'; }
function home(){ mount(`<section class="bg-gradient-to-br from-blue-700 to-slate-950 text-white"><div class="mx-auto grid max-w-7xl gap-8 px-6 py-20 md:grid-cols-2"><div><p class="font-bold uppercase tracking-widest text-blue-200">CCTV & Security ERP</p><h1 class="mt-4 text-5xl font-black">Manage and advertise your complete CCTV business.</h1><p class="mt-5 text-lg text-blue-100">Capture leads, book surveys, generate quotations, reserve inventory, schedule installation, invoice customers, collect payments, sell AMC and resolve complaints.</p><div class="mt-8 flex flex-wrap gap-3"><a class="btn bg-white text-blue-700" href="#/survey">Free Site Survey</a><a class="btn border border-white text-white" href="https://wa.me/${AppConfig.company.whatsapp}">WhatsApp</a></div></div><div class="card bg-white/10 p-6 text-white"><h2 class="text-2xl font-black">Why Suryam Supervision?</h2><ul class="mt-4 grid gap-3">${['HD CCTV installation','Biometric and access control','AMC and preventive maintenance','Fast complaint resolution','Transparent pricing'].map(x=>`<li><i class="fa fa-check text-emerald-300"></i> ${x}</li>`).join('')}</ul></div></div></section><section class="mx-auto grid max-w-7xl gap-4 p-6 md:grid-cols-4">${UI.stat('Projects',250,'camera')}${UI.stat('Happy Customers',180,'smile')}${UI.stat('Brands',24,'certificate')}${UI.stat('Support', '24/7','headset')}</section>`, { publicLayout:true }); }
function simplePublic(path){ const name=path || 'services'; mount(`<section class="mx-auto max-w-5xl p-8"><h1 class="text-4xl font-black capitalize">${name}</h1><p class="mt-4 text-lg text-slate-600 dark:text-slate-300">Professional CCTV cameras, NVR/DVR, access control, networking, maintenance and security automation solutions for homes, shops, societies, warehouses and offices.</p><a class="btn btn-primary mt-6" href="#/survey">Request Consultation</a></section>`, { publicLayout:true }); }
function survey(){ mount(`<section class="mx-auto max-w-2xl p-6"><form class="card p-6"><h1 class="text-3xl font-black">Book Free Site Survey</h1><input class="input mt-4" placeholder="Name"><input class="input mt-3" placeholder="Phone"><textarea class="input mt-3" placeholder="Address / Requirement"></textarea><button class="btn btn-primary mt-4" type="button">Submit Request</button></form></section>`, { publicLayout:true }); }
new Router({ home, services:simplePublic, products:simplePublic, projects:simplePublic, testimonials:simplePublic, pricing:simplePublic, faq:simplePublic, blog:simplePublic, contact:simplePublic, survey, login:()=>mount(loginPage(), { after: bindLogin }), dashboard:()=>mount(dashboardPage()), crm:async()=>mount(await crmPage(), { after: bindCrm }), customers:()=>mount(customersPage()), inventory:()=>mount(inventoryPage()), installation:()=>mount(installationPage()), service:()=>mount(servicePage()), amc:()=>mount(amcPage()), employees:()=>mount(employeesPage()), accounts:()=>mount(accountsPage()), reports:()=>mount(reportsPage()), settings:()=>mount(settingsPage()) }).start();
