import { AppConfig } from './config.js';
import { escapeHtml } from './utils.js';
export const UI = {
  toast(message, type = 'success') { const root = document.getElementById('toast-root'); const el = document.createElement('div'); const colors = { success: 'bg-emerald-600', error: 'bg-rose-600', info: 'bg-blue-600', warning: 'bg-amber-600' }; el.className = `rounded-xl px-4 py-3 shadow-lg text-white ${colors[type] || colors.success}`; el.textContent = message; root.append(el); setTimeout(() => el.remove(), 3500); },
  success(message) { this.toast(message, 'success'); },
  errorToast(message) { this.toast(message, 'error'); },
  info(message) { this.toast(message, 'info'); },
  spinner(label = 'Loading') { return `<div class="grid place-items-center p-10 text-slate-500"><i class="fa fa-spinner fa-spin text-2xl text-blue-600"></i><span class="mt-3 font-semibold">${escapeHtml(label)}</span></div>`; },
  empty(titleText = 'No records', message = 'Nothing to show yet.') { return `<div class="card p-8 text-center"><i class="fa fa-inbox text-3xl text-slate-400"></i><h2 class="mt-3 text-xl font-black">${escapeHtml(titleText)}</h2><p class="mt-1 text-slate-500">${escapeHtml(message)}</p></div>`; },
  error(titleText = 'Something went wrong', message = 'Please try again.') { return `<div class="rounded-2xl border border-rose-200 bg-rose-50 p-6 text-rose-800"><strong>${escapeHtml(titleText)}</strong><p>${escapeHtml(message)}</p></div>`; },
  skeleton(lines = 4) { return `<div class="card space-y-3 p-5">${Array.from({length:lines},()=>'<div class="h-4 animate-pulse rounded bg-slate-200 dark:bg-slate-800"></div>').join('')}</div>`; },
  confirm(message, onConfirmLabel = 'Confirm') { return `<dialog id="confirm-dialog" class="rounded-2xl p-0"><div class="p-5"><h3 class="text-lg font-black">Are you sure?</h3><p class="mt-2">${escapeHtml(message)}</p><div class="mt-4 flex justify-end gap-2"><button class="btn btn-secondary" value="cancel">Cancel</button><button class="btn btn-primary" value="confirm">${escapeHtml(onConfirmLabel)}</button></div></div></dialog>`; },
  modal(id, content) { return `<dialog id="${escapeHtml(id)}" class="w-full max-w-2xl rounded-2xl p-0">${content}</dialog>`; },
  drawer(id, content) { return `<aside id="${escapeHtml(id)}" class="fixed right-0 top-0 z-50 hidden h-full w-full max-w-md border-l bg-white p-5 shadow-2xl dark:bg-slate-900">${content}</aside>`; },
  publicHeader() { const links = ['About','Services','Products','Projects','Pricing','Testimonials','FAQ','Blog','Contact']; return `<nav class="mx-auto flex max-w-7xl items-center justify-between gap-4 p-4" aria-label="Public navigation"><a href="#/" class="text-xl font-black text-blue-700">${AppConfig.company.name}</a><div class="hidden items-center gap-5 lg:flex">${links.map(x=>`<a class="font-semibold hover:text-blue-600" href="#/${x.toLowerCase()}">${x}</a>`).join('')}<a class="font-semibold hover:text-blue-600" href="#/survey">Free Survey</a></div><div class="flex items-center gap-2"><input aria-label="Website search" class="input hidden w-36 xl:block" placeholder="Search"><button id="theme-toggle" class="btn btn-secondary" aria-label="Toggle theme"><i class="fa fa-moon"></i></button><a class="btn btn-secondary hidden sm:inline-flex" href="#/customer">Customer Portal</a><a class="btn btn-primary" href="#/login">Login</a></div></nav>`; },
  publicFooter() { const serviceLinks = ['CCTV Installation','IP Camera','Access Control','Biometric','Fire Alarm','AMC']; return `<div class="mx-auto grid max-w-7xl gap-8 p-8 md:grid-cols-4"><div><h3 class="text-lg font-black">${AppConfig.company.name}</h3><p class="mt-2 text-slate-600 dark:text-slate-300">${AppConfig.company.tagline}</p><div class="mt-4 flex gap-3"><a aria-label="Facebook" href="#"><i class="fab fa-facebook"></i></a><a aria-label="Instagram" href="#"><i class="fab fa-instagram"></i></a><a aria-label="LinkedIn" href="#"><i class="fab fa-linkedin"></i></a></div></div><div><h4 class="font-bold">Quick Links</h4><div class="mt-3 grid gap-2">${['About','Services','Products','Projects','Pricing','Blog','Contact'].map(x=>`<a href="#/${x.toLowerCase()}">${x}</a>`).join('')}</div></div><div><h4 class="font-bold">Services</h4><div class="mt-3 grid gap-2">${serviceLinks.map(x=>`<a href="#/services/${x.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')}">${x}</a>`).join('')}</div></div><div><h4 class="font-bold">Contact</h4><p class="mt-3">${AppConfig.company.phone}</p><p>${AppConfig.company.email}</p><p>${AppConfig.company.city}</p><p class="mt-2">Mon–Sat, 9:30 AM–7 PM</p><div class="mt-3 flex gap-3"><a href="#/privacy">Privacy Policy</a><a href="#/terms">Terms</a></div></div></div>`; },
  shell(content, active = 'dashboard') { const menu = AppConfig.modules.map(m => `<a class="flex items-center gap-3 rounded-xl px-3 py-2 font-semibold ${active===m?'bg-blue-600 text-white':'hover:bg-slate-100 dark:hover:bg-slate-800'}" href="#/${m}"><i class="fa fa-${icon(m)} w-5"></i>${title(m)}</a>`).join(''); return `<div class="flex min-h-screen"><aside class="hidden w-72 border-r border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900 lg:block"><h1 class="mb-6 text-2xl font-black text-blue-700">Suryam ERP</h1><nav class="space-y-1">${menu}</nav></aside><section class="flex-1"><header class="flex items-center justify-between border-b border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><strong>${title(active)}</strong><button id="theme-toggle" class="btn btn-secondary"><i class="fa fa-moon"></i></button></header><main class="p-4 md:p-6">${content}</main></section></div>`; },
  stat(label, value, iconName) { return `<div class="card p-5"><div class="flex items-center justify-between"><span class="text-sm font-bold text-slate-500">${label}</span><i class="fa fa-${iconName} text-blue-600"></i></div><div class="mt-3 text-3xl font-black">${value}</div></div>`; },
  table(headers, rows) { return `<div class="table-wrap bg-white dark:bg-slate-900"><table class="w-full"><thead><tr>${headers.map(h=>`<th>${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows || `<tr><td colspan="${headers.length}">${this.empty()}</td></tr>`}</tbody></table></div>`; },
  dataTable({ headers = [], rows = [], caption = '', actions = '' } = {}) { return `<section class="card overflow-hidden"><div class="flex items-center justify-between p-4"><strong>${escapeHtml(caption)}</strong><div>${actions}</div></div>${this.table(headers, rows)}</section>`; },
  form(fields, submitLabel='Save') { return `<form id="entity-form" class="card grid gap-4 p-5 md:grid-cols-2">${fields.map(f=>`<label class="grid gap-2"><span class="font-bold">${f.label}</span><input class="input" name="${f.name}" type="${f.type||'text'}" ${f.required?'required':''}></label>`).join('')}<button class="btn btn-primary md:col-span-2" type="submit">${submitLabel}</button></form>`; }
};
const title = s => s.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const icon = m => ({dashboard:'chart-line',profile:'user',company:'building',branches:'code-branch',users:'users-gear',roles:'user-shield',permissions:'key',activity:'clock-rotate-left',crm:'bullhorn',customers:'users',inventory:'boxes',installation:'screwdriver-wrench',service:'headset',amc:'shield-halved',employees:'id-card',accounts:'file-invoice-dollar',reports:'chart-pie',settings:'gear'}[m] || 'circle');
