import { AppConfig } from './config.js';
import { escapeHtml } from './utils.js';
export const UI = {
  toast(message, type = 'success') { const root = document.getElementById('toast-root'); const el = document.createElement('div'); el.className = `rounded-xl px-4 py-3 shadow-lg text-white ${type === 'error' ? 'bg-rose-600' : 'bg-emerald-600'}`; el.textContent = message; root.append(el); setTimeout(() => el.remove(), 3500); },
  publicHeader() { return `<nav class="mx-auto flex max-w-7xl items-center justify-between p-4"><a href="#/" class="text-xl font-black text-blue-700">${AppConfig.company.name}</a><div class="hidden gap-6 md:flex">${['Services','Products','Projects','Pricing','FAQ','Contact'].map(x=>`<a class="font-semibold hover:text-blue-600" href="#/${x.toLowerCase()}">${x}</a>`).join('')}</div><div class="flex gap-2"><a class="btn btn-secondary" href="tel:${AppConfig.company.phone}"><i class="fa fa-phone"></i></a><a class="btn btn-primary" href="#/login">Login</a></div></nav>`; },
  publicFooter() { return `<div class="mx-auto grid max-w-7xl gap-6 p-8 md:grid-cols-3"><div><h3 class="text-lg font-black">${AppConfig.company.name}</h3><p class="mt-2 text-slate-600 dark:text-slate-300">${AppConfig.company.tagline}</p></div><div><h4 class="font-bold">Contact</h4><p>${AppConfig.company.phone}</p><p>${AppConfig.company.email}</p></div><div><h4 class="font-bold">Quick Actions</h4><a class="text-blue-600" href="#/survey">Book a free site survey</a></div></div>`; },
  shell(content, active = 'dashboard') { const menu = AppConfig.modules.map(m => `<a class="flex items-center gap-3 rounded-xl px-3 py-2 font-semibold ${active===m?'bg-blue-600 text-white':'hover:bg-slate-100 dark:hover:bg-slate-800'}" href="#/${m}"><i class="fa fa-${icon(m)} w-5"></i>${title(m)}</a>`).join(''); return `<div class="flex min-h-screen"><aside class="hidden w-72 border-r border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900 lg:block"><h1 class="mb-6 text-2xl font-black text-blue-700">Suryam ERP</h1><nav class="space-y-1">${menu}</nav></aside><section class="flex-1"><header class="flex items-center justify-between border-b border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-slate-900"><strong>${title(active)}</strong><button id="theme-toggle" class="btn btn-secondary"><i class="fa fa-moon"></i></button></header><main class="p-4 md:p-6">${content}</main></section></div>`; },
  stat(label, value, iconName) { return `<div class="card p-5"><div class="flex items-center justify-between"><span class="text-sm font-bold text-slate-500">${label}</span><i class="fa fa-${iconName} text-blue-600"></i></div><div class="mt-3 text-3xl font-black">${value}</div></div>`; },
  table(headers, rows) { return `<div class="table-wrap bg-white dark:bg-slate-900"><table class="w-full"><thead><tr>${headers.map(h=>`<th>${escapeHtml(h)}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`; },
  form(fields, submitLabel='Save') { return `<form id="entity-form" class="card grid gap-4 p-5 md:grid-cols-2">${fields.map(f=>`<label class="grid gap-2"><span class="font-bold">${f.label}</span><input class="input" name="${f.name}" type="${f.type||'text'}" ${f.required?'required':''}></label>`).join('')}<button class="btn btn-primary md:col-span-2" type="submit">${submitLabel}</button></form>`; }
};
const title = s => s.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const icon = m => ({dashboard:'chart-line',crm:'bullhorn',customers:'users',inventory:'boxes',installation:'screwdriver-wrench',service:'headset',amc:'shield-halved',employees:'id-card',accounts:'file-invoice-dollar',reports:'chart-pie',settings:'gear'}[m] || 'circle');
